---
# Used to speed up Vagrant-based installs by copying packages locally
# Files will be copied to your Vagrant shared/installers folder if not present

- name: Check for consul ui installer (Vagrant)
  stat: path=/home/vagrant/shared/installers/{{ consul_ui.installer_filename }}
  register: consul_ui_installer_filepath

- name: Get consul ui installer if not present (Vagrant)
  get_url:
    url: "{{ consul_installer.url_base }}/{{ consul_version }}/{{ consul_ui.installer_filename }}"
    dest: "/home/vagrant/shared/installers/{{ consul_ui.installer_filename }}"
  run_once: true
  when: consul_ui_installer_filepath.stat.exists == false

- name: Extract consul ui
  command: unzip -qo /home/vagrant/shared/installers/{{ consul_ui.installer_filename }} -d {{ consul_ui.install_dir }}

- name: Replace exisiting Supervisor file for consul
  template:
    src: consul-with-ui-supervisor.conf.j2
    dest: /etc/supervisor/conf.d/consul-supervisor.conf
    owner: root
    group: supervisor
    mode: 644

- name: Reread supervisor config for consul ui
  command: supervisorctl reread

- name: Restart consul with supervisor
  command: supervisorctl update

- name: Verify consul with ui is running in supervisor
  command: sup status consul
  register: result
  until:
    - "'RUNNING' in result.stdout"
  delay: 15
  retries: 20

- name: Verify consul ui appears
  uri:
    url: http://127.0.0.1:{{ consul_config.http_port }}/ui/
    return_content: yes
  register: result
  until:
    - "'<!DOCTYPE html>' in result.content"
  delay: 3
  retries: 1
